"""Database creation11

Revision ID: 220d151fbb4a
Revises: 697d8719a916
Create Date: 2024-01-10 21:36:25.061415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220d151fbb4a'
down_revision: Union[str, None] = '697d8719a916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='name of courier'),
    sa.Column('number_completed', sa.Integer(), nullable=False, comment='number of completed orders'),
    sa.Column('registration_at', sa.DateTime(timezone=True), nullable=False, comment='time of registration'),
    sa.PrimaryKeyConstraint('sid'),
    schema='public',
    comment='Table with all Courier'
    )
    op.create_index(op.f('ix_public_courier_name'), 'courier', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_courier_sid'), 'courier', ['sid'], unique=True, schema='public')
    op.create_table('district',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='name of courier'),
    sa.PrimaryKeyConstraint('sid'),
    schema='public',
    comment='Table with District data'
    )
    op.create_index(op.f('ix_public_district_name'), 'district', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_district_sid'), 'district', ['sid'], unique=True, schema='public')
    op.create_table('courier_x_district',
    sa.Column('courier_sid', sa.Uuid(), nullable=False),
    sa.Column('district_sid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['courier_sid'], ['public.courier.sid'], ),
    sa.ForeignKeyConstraint(['district_sid'], ['public.district.sid'], ),
    sa.PrimaryKeyConstraint('courier_sid', 'district_sid'),
    schema='public',
    comment='Table with districts for Courier'
    )
    op.create_table('order',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='name of order'),
    sa.Column('status', sa.String(), nullable=False, comment='status of order: 1 - in work, 2 - completed'),
    sa.Column('courier_sid', sa.Uuid(), nullable=False),
    sa.Column('district_sid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['courier_sid'], ['public.courier.sid'], ),
    sa.ForeignKeyConstraint(['district_sid'], ['public.district.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    schema='public',
    comment='Table with orders data'
    )
    op.create_index(op.f('ix_public_order_name'), 'order', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_order_sid'), 'order', ['sid'], unique=True, schema='public')
    op.create_index(op.f('ix_public_order_status'), 'order', ['status'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_order_status'), table_name='order', schema='public')
    op.drop_index(op.f('ix_public_order_sid'), table_name='order', schema='public')
    op.drop_index(op.f('ix_public_order_name'), table_name='order', schema='public')
    op.drop_table('order', schema='public')
    op.drop_table('courier_x_district', schema='public')
    op.drop_index(op.f('ix_public_district_sid'), table_name='district', schema='public')
    op.drop_index(op.f('ix_public_district_name'), table_name='district', schema='public')
    op.drop_table('district', schema='public')
    op.drop_index(op.f('ix_public_courier_sid'), table_name='courier', schema='public')
    op.drop_index(op.f('ix_public_courier_name'), table_name='courier', schema='public')
    op.drop_table('courier', schema='public')
    # ### end Alembic commands ###
