"""Added courier columns

Revision ID: 6bd41135858e
Revises: 220d151fbb4a
Create Date: 2024-01-14 19:16:22.206456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd41135858e'
down_revision: Union[str, None] = '220d151fbb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('avg_order_complete_time', sa.Interval(), nullable=True, comment='average order complete time'))
    op.add_column('courier', sa.Column('avg_day_orders', sa.Integer(), nullable=True, comment='average number of completed orders per day'))
    op.drop_constraint('courier_x_district_courier_sid_fkey', 'courier_x_district', type_='foreignkey')
    op.drop_constraint('courier_x_district_district_sid_fkey', 'courier_x_district', type_='foreignkey')
    op.create_foreign_key(None, 'courier_x_district', 'district', ['district_sid'], ['sid'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'courier_x_district', 'courier', ['courier_sid'], ['sid'], source_schema='public', referent_schema='public')
    op.drop_constraint('order_courier_sid_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_district_sid_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'courier', ['courier_sid'], ['sid'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'order', 'district', ['district_sid'], ['sid'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='public', type_='foreignkey')
    op.create_foreign_key('order_district_sid_fkey', 'order', 'district', ['district_sid'], ['sid'])
    op.create_foreign_key('order_courier_sid_fkey', 'order', 'courier', ['courier_sid'], ['sid'])
    op.drop_constraint(None, 'courier_x_district', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'courier_x_district', schema='public', type_='foreignkey')
    op.create_foreign_key('courier_x_district_district_sid_fkey', 'courier_x_district', 'district', ['district_sid'], ['sid'])
    op.create_foreign_key('courier_x_district_courier_sid_fkey', 'courier_x_district', 'courier', ['courier_sid'], ['sid'])
    op.drop_column('courier', 'avg_day_orders')
    op.drop_column('courier', 'avg_order_complete_time')
    # ### end Alembic commands ###
