"""Added registration_at for order

Revision ID: d0f27e961dcf
Revises: 6bd41135858e
Create Date: 2024-01-15 14:13:24.382621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f27e961dcf'
down_revision: Union[str, None] = '6bd41135858e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courier_x_district_district_sid_fkey', 'courier_x_district', type_='foreignkey')
    op.drop_constraint('courier_x_district_courier_sid_fkey', 'courier_x_district', type_='foreignkey')
    op.create_foreign_key(None, 'courier_x_district', 'district', ['district_sid'], ['sid'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'courier_x_district', 'courier', ['courier_sid'], ['sid'], source_schema='public', referent_schema='public')
    op.add_column('order', sa.Column('registration_at', sa.DateTime(timezone=True), nullable=False, comment='time of registration'))
    op.drop_constraint('order_courier_sid_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_district_sid_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'courier', ['courier_sid'], ['sid'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'order', 'district', ['district_sid'], ['sid'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order', schema='public', type_='foreignkey')
    op.create_foreign_key('order_district_sid_fkey', 'order', 'district', ['district_sid'], ['sid'])
    op.create_foreign_key('order_courier_sid_fkey', 'order', 'courier', ['courier_sid'], ['sid'])
    op.drop_column('order', 'registration_at')
    op.drop_constraint(None, 'courier_x_district', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'courier_x_district', schema='public', type_='foreignkey')
    op.create_foreign_key('courier_x_district_courier_sid_fkey', 'courier_x_district', 'courier', ['courier_sid'], ['sid'])
    op.create_foreign_key('courier_x_district_district_sid_fkey', 'courier_x_district', 'district', ['district_sid'], ['sid'])
    # ### end Alembic commands ###
