name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: 
          - "5432:5432"
        env: 
          POSTGRES_DB: courier_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 111
    env:
      POSTGRES_DB: courier_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      RAILS_ENV: tests
      DATABASE_URL: "postgres://postgres:111@localhost:5432/courier_db"
      POSTGRES_DB_TEST: courier_db
      POSTGRES_USER_TEST: postgres
      POSTGRES_PASSWORD_TEST: 111
      POSTGRES_HOST_TEST: localhost
      POSTGRES_PORT_TEST: 5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v1
      with:
           python-version: '3.11'
           architecture: 'x64'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Upgrade DB
      run: alembic upgrade head
    - name: Run tests
      run: pytest
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Ruby and gems
          uses: actions/setup-python@v1
          with:
            python-version: '3.11'
            architecture: 'x64'
        - name: Run command on remote server
          uses: D3rHase/ssh-command-action@v0.2.2
          with:
            host: 90.188.20.234
            port: 3683
            user: danil
            private_key: -----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAi1d6MtiMBYxLZlj82gZDRwKGE/A2k5zOBLwwgcAwghukKT/JLS8d3Vs0Pzfytz0GL0VhJBoyR9vuOjlsadOXhhI/kgfk/1WbIrtqdaipHl6EZ8b6X5eBRgkbyz/Ic60EvFVp23YuMNVCyeLD7zfV4CwG0NgY3BOAsmOGmuw+G+m3G8T5r3wO2UbVkxHS+Zwex3WGN6i+mY1OGW+pxt4Y/0hkyAkU9f2DImMBpCldd+iwW+N9PjFzvxzLx/D1wtc21LTq/RjQycgGFbDOgMEgZxB6eKmBORtIDd+DiEg3TGQ4iDLcbwtb5owea9ALiRIhP03EJB/Yhbo2RGROHyPUo9+JgPFSO1wZgLAwWOTaJpL8osA00Jh6rRo/NUCv0aEV3CrNFsA1xmIXNnLbwcReY1KS1sP2jctWHJ8QbmPVZz5iQtL8BL62KzBH0Kg2G5TTuMa3aEaA71vnGANZ8NjKw2vpRdM6Yox6HHMMK97l+0qsbhFj3nQ1B0VIAwRyjqKnAAAFkE1GgqNNRoKjAAAAB3NzaC1yc2EAAAGBAItXejLYjAWMS2ZY/NoGQ0cChhPwNpOczgS8MIHAMIIbpCk/yS0vHd1bND838rc9Bi9FYSQaMkfb7jo5bGnTl4YSP5IH5P9VmyK7anWoqR5ehGfG+l+XgUYJG8s/yHOtBLxVadt2LjDVQsniw+831eAsBtDYGNwTgLJjhprsPhvptxvE+a98DtlG1ZMR0vmcHsd1hjeovpmNThlvqcbeGP9IZMgJFPX9gyJjAaQpXXfosFvjfT4xc78cy8fw9cLXNtS06v0Y0MnIBhWwzoDBIGcQenipgTkbSA3fg4hIN0xkOIgy3G8LW+aMHmvQC4kSIT9NxCQf2IW6NkRkTh8j1KPfiYDxUjtcGYCwMFjk2iaS/KLANNCYeq0aPzVAr9GhFdwqzRbANcZiFzZy28HEXmNSktbD9o3LVhyfEG5j1Wc+YkLS/AS+tiswR9CoNhuU07jGt2hGgO9b5xgDWfDYysNr6UXTOmKMehxzDCve5ftKrG4RY950NQdFSAMEco6ipwAAAAMBAAEAAAGALCgyHOfb46w0fsAnjO4cJuYpWCsxGHFCJmT+2DdwB+M7kCjbF3sNc0cCVSBlReVMTvGlGZxFn9kV8xScgyLfK0kgJSZkTvgxe/25fITQ50NboUmAsYdhG7EqQiw52VKUpBxLOhWHCMmkazb2EZp3qB07obZBloiFqcJ5dyHzgsP7V40B9TcSu49DgmJNIfX0GRBo0r2ifSW3AL+OpWtfr5KhAXVDU7sdcem/LOdA7A1sygna+DkSrZcyCvAU6cRqb56wY8FoqEasHCJN6655d1uXr788WPsuj1Wq+SO8BmTG4K4gz0NpKCuHVtFbOZh5ceTeOqeqvLtjOZEnXfDV02Ij73mIDcneiaqVUKOITSsa2dLGZ+vU2EM5lpScBOvxycLTyiiCe/wJjFOGfNpuymxC1Wm/lNffQqm4TOBc3mAaM9GWJ+BgbGp/0Wfdg2PavBPT2TGwwcZ4KgY0vVAqJA+KlB9Kf+ivgKv5Xh4vY0j+fea3v81vM8klg6ZPfl/pAAAAwFdacem933MnJvv4DMP24kycc8S0vRqcSMWk1eHCD0xuPIZ5ZcFfwPxoT+Dd+quYI3NuTU17O1AGEd5PdTAOLzY3U3s/KlLGO8fsr8DGOmEri9jGA0/Dc9efVo7OR3zZfKyi+tjtc/AOXagRk1WibozH8Tx4xH0TIWhTS5vBathtMOh0qfIPt21UXfpQHaS7joybIdDnTXRSmBcihONnZgGrytlnjhkOB5seEG9nTop1h7Jr/MaFWihoI1LZb1YoQAAAAMEAuVtbIfiw0h/STSsefCXMNPF0E7i/ek81mWZpfehjZcuxZ8NBxeM81QQAjBI5K/Qq4fZJP6ulWgwFl8i7r+ZTpTxW53fMP3wtToC1wpZKf3QayuSQU1e+3PvqQ9zpJh+KOpmGajHuw9fB1JAsuWR/bsNn1HAhSIuJhuqaV6yQXyeas/Rti14iZHEIXeLZFifPCZc5vkBBOHfJGHjFE0YKeQW5Smmc8d8xQhk6a5eoFhHXASI1vkwvq2c5UtdiPEcZAAAAwQDAcpQCuGGSemxwCEdMsU4SV9Ys8VjpwRBrwWkXgvyVE++eJwU/hfTuCSFjjqLKbk+tR8yljcQeFs3yY4M11w5k0Tho89AWBRUkzb/iGO4NQHimoyRPqsSTap2F3uJkPEfxzfOzB5K7FyGG7N+uIMbUB4NkoqXcuOXwjn2J8NGDHmVw9LUTF7yyPjy+bYn/NwolTulj3lMMefN0L/FJz+vX0TcqlLsppm6lth/yyO75618WbOHuEnMie+FhBkPIL78AAAAWZGFuaWxAZGFuaWwtQjM2NU0tRFMzSAECAwQF-----END OPENSSH PRIVATE KEY-----
              docker-compose --file docker-compose.prod.yml down;
              docker-compose --file docker-compose.prod.yml up -d;
              docker system prune --all --force;
