name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: 
          - "5432:5432"
        env: 
          POSTGRES_DB: courier_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 111
    env:
      POSTGRES_DB: courier_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      RAILS_ENV: tests
      DATABASE_URL: "postgres://postgres:111@localhost:5432/courier_db"
      POSTGRES_DB_TEST: courier_db
      POSTGRES_USER_TEST: postgres
      POSTGRES_PASSWORD_TEST: 111
      POSTGRES_HOST_TEST: localhost
      POSTGRES_PORT_TEST: 5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v1
      with:
           python-version: '3.11'
           architecture: 'x64'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Upgrade DB
      run: alembic upgrade head
    - name: Run tests
      run: pytest
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Ruby and gems
          uses: actions/setup-python@v1
          with:
            python-version: '3.11'
            architecture: 'x64'
        - name: Run command on remote server
          uses: D3rHase/ssh-command-action@v0.2.2
          with:
            host: 90.188.20.234
            port: 3683
            user: danil
            password: tj6yhl
            private_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD3P2GXvDuMGvohxdvfIU0mUx3pHnh00YM5BbSRTI/YPQcTgATf1cuJbRz8C6h9MVF+9w0Id1gvokHjKYIBZaAmnTvY1octl+Tb+XACsaey/iDyf2vRkRJG3AWcPDBezgKsdDSXEfICtEakskJAeXWP+nwfvIkI1ihjvClaqDe0DdYWxvpvTZ5hzu/7uDkZKkmTkzjIqf26SnzGb/PbjoV6+QmAcc/JFlRPUZXc69jj5xhmtykpvJbXzAxzfIW5Wp2Q3VobjUmrh6BdC8p48pWgnh9JPoLR8gffqxikNYYK7rFt3naBkfPsnetu9csyKi5o1YvzH+hSNJCf0g26BowTaw/NgyRKaBT8wOX5/ARcJ6i5VsnqHgEjVxAki8k2XrIuzQM2x8cttvPeaNXTQGqTUvjTCnz1Zb3VkYE6Zid/Fyz+HupddP/wRpVHJHyxLL29mA/Orbe4D5gt2P02qHigh9ivOBGdbEXzakWQNbgLqHIgAAZhHyY54qxKd0lEZc= root@danil-B365M-DS3H
              docker-compose --file docker-compose.prod.yml down;
              docker-compose --file docker-compose.prod.yml up -d;
              docker system prune --all --force;
