name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: 
          - "5432:5432"
        env: 
          POSTGRES_DB: courier_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 111
    env:
      POSTGRES_DB: courier_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      RAILS_ENV: tests
      DATABASE_URL: "postgres://postgres:111@localhost:5432/courier_db"
      POSTGRES_DB_TEST: courier_db
      POSTGRES_USER_TEST: postgres
      POSTGRES_PASSWORD_TEST: 111
      POSTGRES_HOST_TEST: localhost
      POSTGRES_PORT_TEST: 5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v1
      with:
           python-version: '3.11'
           architecture: 'x64'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Upgrade DB
      run: alembic upgrade head
    - name: Run tests
      run: pytest
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Ruby and gems
          uses: actions/setup-python@v1
          with:
            python-version: '3.11'
            architecture: 'x64'
        - name: Run command on remote server
          uses: D3rHase/ssh-command-action@v0.2.2
          with:
            host: 90.188.20.234
            user: root
            port: 3683
            private_key: -----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAw9z9hl7w7jBr6IcXb3yFNJlMd6R54dNGDOQW0kUyP2D0HE4AE39XLiW0c/AuofTFRfvcNCHdYL6JB4ymCAWWgJp072NaHLZfk2/lwArGnsv4g8n9r0ZESRtwFnDwwXs4CrHQ0lxHyArRGpLJCQHl1j/p8H7yJCNYoY7wpWqg3tA3WFsb6b02eYc7v+7g5GSpJk5M4yKn9ukp8xm/z246FevkJgHHPyRZUT1GV3OvY4+cYZrcpKbyW18wMc3yFuVqdkN1aG41Jq4egXQvKePKVoJ4fST6C0fIH36sYpDWGCu6xbd52gZHz7J3rbvXLMiouaNWL8x/oUjSQn9INugaME2sPzYMkSmgU/MDl+fwEXCeouVbJ6h4BI1cQJIvJNl6yLs0DNsfHLbbz3mjV00Bqk1L40wp89WW91ZGBOmYnfxcs/h7qXXT/8EaVRyR8sSy9vZgPzq23uA+YLdj9Nqh4oIfYrzgRnWxF82pFkDW4C6hyIAAGYR8mOeKsSndJRGXAAAFkLa7YDC2u2AwAAAAB3NzaC1yc2EAAAGBAMPc/YZe8O4wa+iHF298hTSZTHekeeHTRgzkFtJFMj9g9BxOABN/Vy4ltHPwLqH0xUX73DQh3WC+iQeMpggFloCadO9jWhy2X5Nv5cAKxp7L+IPJ/a9GREkbcBZw8MF7OAqx0NJcR8gK0RqSyQkB5dY/6fB+8iQjWKGO8KVqoN7QN1hbG+m9NnmHO7/u4ORkqSZOTOMip/bpKfMZv89uOhXr5CYBxz8kWVE9Rldzr2OPnGGa3KSm8ltfMDHN8hblanZDdWhuNSauHoF0LynjylaCeH0k+gtHyB9+rGKQ1hgrusW3edoGR8+yd6271yzIqLmjVi/Mf6FI0kJ/SDboGjBNrD82DJEpoFPzA5fn8BFwnqLlWyeoeASNXECSLyTZesi7NAzbHxy22895o1dNAapNS+NMKfPVlvdWRgTpmJ38XLP4e6l10//BGlUckfLEsvb2YD86tt7gPmC3Y/TaoeKCH2K84EZ1sRfNqRZA1uAuociAABmEfJjnirEp3SURlwAAAAMBAAEAAAGAEpqeFjJUbjt5NHgIeNV6DZn2EnM0BIg94iGULVrXP//kj/+0sCVrUX3RWyXYOBf42QHoU6dX0MWoXGg2qRJmzkZdjxN/zrRf9bAuQYSEgzbanyIDj6978vnBNtB5fddHZnSnYiPTyaOFYyHIKKveefBON0LHmzkkRQw/vWaYazGZ4DGfQB9x2i9HNJ7rC6aoDnRnhzeWfrR9AJNUjc5phAWJATcwBsZcGYRZdxsM8McGUpsUFCurX5R2DnUCZrxZquF7WrdtZ2K3TuC3nPz1MkGXYM5pzu1ihqqcV0jhKCFlaxiqF8DYpWhjeQ69OvG0TME3MbBuo4AM706PgPQ1h8MY3SzJUV4oGB6BuajmbwRCg8kIjXm5ndhEkANLgAqR12KgL58cH034CjJzl3J3dHNrWNHOzXx0dN8bbDRBQvYyl5QjJVUiBzDbor/c9kwKNauzflHiLTtf+vEJj89tdxEwykbxZH9L+dTf/iyg0wZRLvpFUMbEJjiEX/pSNU7xAAAAwHt0VPTgohBirXf35MQyy396yLuZ03m0z5VMZKmQ7ig5nLlNesG99EHKvj/CGKyFathJSDAyq6lSimcu4E42vEiWJtfdfBY6LWnlxHDaaQhqTXZb7urymJqeoB3fPmKDZB7URy/twBU/w/zhFxGF7rOe+KV9tq4svWeKIu8mV1oGF22BkHlwJ1WNRMQgJBBLwZ02TszEQpdVEXqJOe5AmK9vwQ5aoc8jSMjIXyZxmLUiBJ7jKDtkCijoeT1d8SzdmQAAAMEA3X9NZZzU/AVRdWc3yxgFDp4lIdZ22A3OWNOyAEobyfnin6ClPnSO9FlGFE69OPPU5Cqcf893FRb1gDx9H/N3hbY/71SoWI4fFSxq67LKPR8vvcssJyXGw+RugiK+3kTNFVBg9qumI2ag/vsQiLSfivPfzBftRifH7p3kXiExhNqQMwEK0OGUyOCGKQmBcErMJ9DvjYLAvQXYlRyfnEB9s4PQDt+X9Y9jbP6rw8O8H0TScMs0OTCge17lgOu26+qJAAAAwQDiX3lOVNiBLi4ooZHto5Wb1fJzdJGJ3irLWbc7XQpKzLzc7OAwB/rPYTfKcBd09wh0UHdwlv1yYaGQ5CHsZ0/NO9AmsCUrwdBbf0B0K5phLp64iro6hphuWpxjWbQojpjPu5xW/Eh4lwgu7+vYgPzLivHGzJ5rVaPhi+ns30o4SRdRhSBDiE5Vua6hoP87FX7wyi2eigFFsOTwc438XDzWgfSL7ZTUolikZjYnfPCoBvVpaYbJAbI1xRLjZMHvkx8AAAAVcm9vdEBkYW5pbC1CMzY1TS1EUzNIAQIDBAUG-----END OPENSSH PRIVATE KEY-----
              docker-compose --file docker-compose.prod.yml down;
              docker-compose --file docker-compose.prod.yml up -d;
              docker system prune --all --force;
