name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: 
          - "5432:5432"
        env: 
          POSTGRES_DB: courier_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 111
    env:
      POSTGRES_DB: courier_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      RAILS_ENV: tests
      DATABASE_URL: "postgres://postgres:111@localhost:5432/courier_db"
      POSTGRES_DB_TEST: courier_db
      POSTGRES_USER_TEST: postgres
      POSTGRES_PASSWORD_TEST: 111
      POSTGRES_HOST_TEST: localhost
      POSTGRES_PORT_TEST: 5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v1
      with:
           python-version: '3.11'
           architecture: 'x64'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Upgrade DB
      run: alembic upgrade head
    - name: Run tests
      run: pytest
  deploy:
      needs: tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.11'
            architecture: 'x64'
        - name: Run command on remote server
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.HOST}}
            port: ${{secrets.PORT}}
            username: ${{secrets.USER_NAME}}
            password: ${{secrets.USER_PWD}}
            script: |
              cd ${{secrets.PROJECT_DIR}}
              git pull
              bash deploy.sh
